backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  -name: "docs"
  label: "Docs"
  folder: "src/pages/docs"
  create: true
  slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
  field:
    - {label: "Title", name: "title", widget: "datetime" }
    
